# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_basic-summaries.ipynb.

# %% auto 0
__all__ = []

# %% ../01_basic-summaries.ipynb 5
import pandas as pd
from .Missing import PandasMissing
from fastcore.basics import patch

# %% ../01_basic-summaries.ipynb 6
@patch
def number_missing(self: PandasMissing):
    """Return the number of missing values in the entire DataFrame."""
    return self._df.isna().sum().sum()

# %% ../01_basic-summaries.ipynb 8
@patch
def number_complete(self: PandasMissing):
    """Return the number of non-missing values in the entire DataFrame."""
    return self._df.size - self._df.missing.number_missing()
