# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_pandas-missing-class.ipynb.

# %% auto 0
__all__ = ['PandasMissingDataFrame', 'PandasMissingSeries']

# %% ../00_pandas-missing-class.ipynb 3
import pandas as pd

# %% ../00_pandas-missing-class.ipynb 5
@pd.api.extensions.register_dataframe_accessor("missing")
class PandasMissingDataFrame:
    
    def __init__(self, df: pd.DataFrame):
        """Pandas extension that registers a new dataframe accessor called `missing`.
        """

        self._df = df

# %% ../00_pandas-missing-class.ipynb 8
@pd.api.extensions.register_series_accessor("missing")
class PandasMissingSeries:
    
    def __init__(self, series: pd.Series):
        """Pandas extension that registers a new series accessor called `missing`.
        """

        self._s = series
