# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_pandas-missing-class.ipynb.

# %% auto 0
__all__ = ['PandasMissing']

# %% ../00_pandas-missing-class.ipynb 3
import pandas as pd

@pd.api.extensions.register_dataframe_accessor("missing")
class PandasMissing:
    
    def __init__(self, df: pd.DataFrame):
        """Pandas extension that register a new dataframe accessor called `missing`.
        """

        self._df = df
